version: '3.8'

services:
  vprodb:
    build:
      context: ./dockerfiles/db
    image: rajg/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    networks:
      - vpro-net

  vprocache01:
    image: memcached:latest
    container_name: vprocache01
    ports:
      - "11211:11211"
    networks:
      - vpro-net

  vpromq01:
    image: rabbitmq:latest
    container_name: vpromq01
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - vpro-net

  vproapp:
    build:
      context: ./dockerfiles/app
    image: rajg/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    networks:
      - vpro-net
    depends_on:
      - vprodb
      - vprocache01
      - vpromq01

  vproweb:
    build:
      context: ./dockerfiles/web
    image: rajg/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
    depends_on:
      - vproapp
    networks:
      - vpro-net

volumes:
  vprodbdata: {}
  vproappdata: {}

networks:
  vpro-net:
    driver: bridge
