pipeline {
    agent any
    environment {
        // --- ECS PROD Variables ---
        // 🔴 UPDATE THESE TO MATCH YOUR PROD CLUSTER/SERVICE NAMES
        ECS_CLUSTER = "vprofile-app-prod"
        ECS_SERVICE = "vprofile-app-svc-prod"
        AWS_REGION = "ap-south-1"
        
        // Credential ID from Jenkins
        registryCredential = "aws-creds"
    }

    stages {
        stage('Deploy to Prod ECS') {
            steps {
                withCredentials([usernamePassword(credentialsId: registryCredential, passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
                    sh """
                    aws ecs update-service \
                    --cluster ${ECS_CLUSTER} \
                    --service ${ECS_SERVICE} \
                    --force-new-deployment \
                    --region ${AWS_REGION}
                    """
                }
            }
        }
    } 
    
    post {
        always {
            echo 'Deployment to Production initiated.'
        }
    }
}